### ISSUE TITLE
Does this also work with 

### ISSUE THREAD

**Issue by trenkert** [borzunov/remoteink#1]
a) other e-readers like Kindle, Kobo, Onyx, Nook, Icarus?

b) the new Pocketbook models like the Inkpad?

**Comment by borzunov** [comment]
a) No, the client depends on PocketBook API.

b) The client works on Inkpad. Here is a photo of this: http://www.mobileread.com/forums/showpost.php?p=3057292&postcount=13 There's also some notes about running on Inkpad in the previous message of this thread.

**Comment by trenkert** [comment]
thanks a lot!
