### ISSUE TITLE
Remoteink USB connection issues, advice needed

### ISSUE THREAD

**Issue by Devindar-hash** [borzunov/remoteink#11]
Hello Alexander and Nikolai,

I received a request to connect 2 devices together: Raspberry Pi 2 and Pocketbook Inkpad 3 as a screen via USB. Can't manage to get the USB connection via remoteink to work and ask you for any advice you could offer.

Wifi connection works without issues, but the person who made the request wants to avoid using wireless signals. Been trying to use a pl-25a1 USB2 chipset cable & USB2 (female) -> MicroUSB (male) for it. Inkpad 3 has been rooted and got USB networking turned on. When connected together via cable, Raspberry shows USB network IP and port, yet no interface pops up in remoteink, so I believe the issue could be on the Pocketbook side of things.

Do you know of compatibility between remoteink and Inkpad 3?
Do you know of any way to check if Inkpad 3 contains g_ether module?
Could the adapter be an issue in the USBNet connection?
Is the cable good for what I'm trying to do?

**Comment by borzunov** [comment]
Hi @Devindar-hash!

Unfortunately, I can't help much with the issue you have described.

> Do you know of compatibility between remoteink and Inkpad 3?

I have not tried remoteink on InkPad 3 myself but I saw a [thread](https://www.mobileread.com/forums/showthread.php?t=325673) with people trying that. Someone wrote that rooting may help, however there are no reports where people managed to make it work via USB.

> Do you know of any way to check if Inkpad 3 contains g_ether module?

I don't know for sure, but using a terminal to explore the internal file system may help.

> Could the adapter be an issue in the USBNet connection? Is the cable good for what I'm trying to do?

I don't know for sure, but I doubt the cable model makes a difference here (in case if you know that your cable is not corrupted).

**Comment by Devindar-hash** [comment]
Thank you for the reply @borzunov!

I will try looking through the system, otherwise a lack of records on the net of the USB connection between those 2 devices being possible is somewhat disheartening.

Have a great day!
