### ISSUE TITLE
Can it work for Windows 10 ?

### ISSUE THREAD

**Issue by drdima2** [borzunov/remoteink#13]
Hi, I have PocketBook Inkpad X. It's 10 inch screen device.
Can your client application work under Windows 10 OS ?
Thanks

**Comment by borzunov** [comment]
Hi Dmitry!

Unfortunately, I doubt it can work for native Windows 10 apps. There is a small chance that it may work for something run on WSL (Windows Subsystem for Linux), however, I've never heard of anyone trying that.
