### ISSUE TITLE
Supporting colored e-book (Pocketbook 740 Color)

### ISSUE THREAD

**Issue by avnya** [borzunov/remoteink#14]
Hey! Is is possible to support color E-book, e.g. PocketBook 740 Color?

**Comment by borzunov** [comment]
Hey!

It's most likely that this model is supported but the screen will be displayed in black & white. Displaying the screen in color is  technically feasible but, unfortunately, I don't have an opportunity to implement it now or in the nearest future :(

Of course, if anyone is willing to help, pull requests of sufficient quality are welcome :)

If you decide that the black & white screen is enough but it wouldn't work, feel free to re-open this issue.
