### ISSUE TITLE
keyboard

### ISSUE THREAD

**Issue by urbocc** [borzunov/remoteink#16]
Hi, I have a question with my pocketbook, it is possible to use a keyboard to write in the book?

**Comment by borzunov** [comment]
Hi @urbocc,

Remoteink allows to connect your e-book as a computer monitor. This means that if you type something with your computer's keyboard, it will be shown on the e-book.

Also, there's a chance that you can connect a keyboard to the e-book directly via USB (without using a computer and Remoteink), but I'm not sure if it works and if there's a good software to edit text right on the e-book.
