### ISSUE TITLE
On Pocketbook Touch new firmware (5.14 in my case) client screen is shifted down

### ISSUE THREAD

**Issue by rolandas** [borzunov/remoteink#6]
Privet Aleksandr...

First of all - remoteink is wonderfull aplication. We have excellent use of it in sailplane cockpit as BeagleBoneBlack microcomputer screen - due to bright sunlight PaperInk is one of very few options with low power consumption... Transflective screens on phones or touchpads are extremely rare now...

We have mostly PocketBooks in the stores overhere (in Lithuania). Kindles and Kobos are only ordered online and should be illegaly rooted. Kindle Keyboard is our current screen, but we like PocketBook Touch, becuse using your application we do not need to be involved in hacking it...
 
RemoteInk is perfectly working on our Pocketbook Touch Lux2 (model 626) with 4.xx firmware, but it is obsolete now for several years. In 5.xx firmware client's screen is shifted down (I think it is somehow related to Status Bar - this is the size of shift down).

Please find some spare time and fix this for new PocketBook firmware. THANKS...

Respectfully,
Rolandas RAGAISIS
Kaunas, Lithuania...

P.S. You are welcome to visit us and fly our sailplanes in Lithuanian skies...

**Comment by borzunov** [comment]
Hi Rolandas!

I've added a fix to eliminate this problem. Try using new [remoteink.app](https://github.com/borzunov/remoteink/raw/master/client/dist/remoteink.app) on your reader.

P. S. If possible, could you send a photo of remoteink running in a sailplane cockpit? :)
